title: DentOS documentation
description: Documentation
theme: just-the-docs

url: https://dentproject.github.io/docs.dent.dev

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
